version: '3.4'

services:
  hotelmanagementsystem:
    image: hotelmanagementsystem
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3009:3009
